### ISSUE TITLE
Examples ≠ Tests

### ISSUE THREAD

**Issue by edbennett** [LupoA/lsdensities#30]
I'm assuming that the primary purpose of the repository is the library, with the `exec` directory giving example tools that can use it. In that case I would suggest renaming the `exec` directory to `examples`, and removing `test` from the filenames in there (otherwise pytest may complain).

I'd suggest adding them to `[project.scripts]` if you expect users to call them as programs routinely.

**Comment by nickforce989** [comment]
This should be closed, I think. @edbennett
