### ISSUE TITLE
Use a code style checker

### ISSUE THREAD

**Issue by edbennett** [LupoA/lsdensities#31]
In addition to autoformatting (see #25), `ruff` can also check for more increasingly pedantic things that it can't automatically fix. I wouldn't suggest enabling everything, but would suggest we discuss what categories of warning are a good starting point.

For example, I would definitely want to try and get rid of any lines including `import *`, and more broadly any imports that aren't used.

**Comment by nickforce989** [comment]
Done. I don't get any error anymore when ruff check is ran.

**Comment by edbennett** [comment]
One more thing, sorry: can you add the configuration block for this to `pyproject.toml`? This will provide a starting point for further tidying later.e

**Comment by nickforce989** [comment]
May I ask what should I add?

**Comment by edbennett** [comment]
Oops, I was planning to include that in the previous message, but got side-tracked, rewrote the message, and forgot it.

The `tool.ruff.lint` block from [the ruff README](https://github.com/astral-sh/ruff)
