### ISSUE TITLE
`plt.clf(); plt.close(fig)` is redundant

### ISSUE THREAD

**Issue by edbennett** [LupoA/lsdensities#36]
Closing a figure destroys it and everything in it; you don't need to call `plt.clf()` beforehand to clear it.

**Comment by nickforce989** [comment]
I should have solved this one.

**Comment by edbennett** [comment]
In a pull request or on the main branch?

**Comment by nickforce989** [comment]
Main branch.

**Comment by edbennett** [comment]
`plt.show(); plt.clf()` is also redundant
