### ISSUE TITLE
Use pytest

### ISSUE THREAD

**Issue by edbennett** [LupoA/lsdensities#42]
Currently the `tests` directory contains programs with a `main()` function that outputs the result of a check; it would be better to use an automated testing tool like `pytest` for this instead—this will reduce the amount of code, make it more easily automated, and make it easier to read for others who are already familiar with pytest.

**Comment by edbennett** [comment]
This is still open: currently running `pytest` gives the message "no tests ran".

Current issues:

- [ ] [pytest will only test functions with names starting with `test`](https://docs.pytest.org/en/6.2.x/goodpractices.html#test-discovery)
- [ ] `test_import` is redundant, since all other tests will perform a similar import that fails. 
- [ ] The code in `test_invert.py` should be in a function.
- [ ] You don't need to call the test functions (like is done in `test_periodicity.py`) once they are named such that `pytest` will pick them up
- [ ] Tests should in general have some assertion of correctness—both `test_invert.py` and `test_setprec.py` have an `init_precision` function that doesn't seem to do anything. (Note that `print` outputs will be swallowed by `pytest` to avoid cluttering output.)

If anything's unclear, I'd suggest having a read of an introductory tutorial on using pytest (e.g. [this one](https://edbennett.github.io/python-testing-ci/))

**Comment by LupoA** [comment]
pytest fails finding modules for me on all tests

ModuleNotFoundError: No module named 'lsdensities'

I am in the virtual env

**Comment by LupoA** [comment]
Indeed the tests should have assertions. I am planning to write a new bunch of them in the close future, the ones that we have now are very basic.

test_periodicity is I think one of the most useful and was badly set up to produce plots for visual inspection, no assertions. We can put one on the values of f_t at large t matching f_t at infinite t.

It seems to be this test was broken since the S_matrix plot has now more content than it should have.

**Comment by LupoA** [comment]
possibly solved by 4f2f701

**Comment by LupoA** [comment]
> pytest fails finding modules for me on all tests ( ModuleNotFoundError: No module named 'lsdensities')
> 
> while python -m pytest works

this persists but I don't think it is a problem

**Comment by edbennett** [comment]
If `pytest` does not work but `python -m pytest` does, then this is an issue with your setup—you have `pytest` installed in your `PATH` somewhere that has higher precedence than your current virtual environment, and so it runs with the environment it's installed in rather than the one you want.

(Using `python -m pytest` by default is frequently a good idea for this reason.)

**Comment by nickforce989** [comment]
Is this issue still to be completed?

**Comment by edbennett** [comment]
- [ ] I'd suggest that `test_integration.py` should have a test function in. You can get timings for how long each test takes using (`python -m`) `pytest --durations=0`. In that case, then the test in that file should actually test something—there should be an `assert` that the value of `integral` is correct.
- [ ] Similarly, it would be good if `test_init_precision` actually checked that the precision has been correctly initialised.
- [ ] The last five lines of `tests/test_periodicity.py`, and the last three lines of `tests/test_setprec.py`  should be removed.
- [ ] What are the files `tests/Smatrix_periodicity_check.png` and `tests/ft_periodicity_check.png` for? They don't seem to be used for anything, and should probably be removed.

**Comment by nickforce989** [comment]
Ok, I should have addressed your points, and there are asserts and pytest success in running too.

**Comment by edbennett** [comment]
I've checked off the bullets that have been addressed from my previous message—looks like there's one test that still doesn't test anything?

**Comment by nickforce989** [comment]
Woops, sorry I didn't notice that. I corrected it now.
