### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by edbennett** [LupoA/lsdensities#45]
Some things would improve the README

- Make HLT a link to where to read more about the method
- Discuss usage in more detail
- Mention `examples`

**Comment by LupoA** [comment]
Should I also change the repository's name according to the package name? I am in favor of that, yet don't want anyone to have a stroke

**Comment by edbennett** [comment]
It would make life simpler for users. So long as you update the README at the same time to match, I don't see an issue.

**Comment by LupoA** [comment]
happy to do more changes, you can close otherwise :)

**Comment by edbennett** [comment]
Thanks Alessandro, that looks a lot better. Could you adjust the example so that it's obvious what sort of data structures are expected for `time_extent`, `parameters`, `energy`, and `lattice_correlator`, please? (And, if I'm allowed to be picky, replace `inputMatrix` with `input_matrix`?)

**Comment by LupoA** [comment]
Added a bit of info. Pickiness is very welcome!

**Comment by edbennett** [comment]
Thanks! My intent is to make it so someone can run the example and have it work—to that end, can you a) add the import for `Inputs`, and b) copy-paste this into a `.py` file and run it and check that it doesn't error, please?

**Comment by LupoA** [comment]
thanks that gives me a better idea. Should I also include the file into the example folder?

**Comment by edbennett** [comment]
That would probably also make sense. :+1:

**Comment by LupoA** [comment]
all done here
