### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by edbennett** [LupoA/lsdensities#47]
`pyproject.toml` defines requirements for installing a package, and that is now done correctly.

`requirements.txt` is useful to let people know what other packages are needed to be able to contribute to development of a project. Currently this is `pre-commit`, but `pytest` is coming soon (#42).

Once that's created, there should be a mention in the README of it. (E.g. a short section on contributing/setting up a development environment.)

**Comment by nickforce989** [comment]
@edbennett Is there a specific format for this file? Or is it just a '.txt' file?

**Comment by edbennett** [comment]
Documentation: https://pip.pypa.io/en/stable/reference/requirements-file-format/

**Comment by nickforce989** [comment]
I might have addressed this issue? @edbennett

**Comment by edbennett** [comment]
You don't need `mpmath` and `progressbar` as they are already required via `pyproject.toml`.

**Comment by nickforce989** [comment]
Corrected.

**Comment by edbennett** [comment]
Regarding the README, the `requirements.txt` only lists the development requirements, so we should move that below the instructions for people who want to use the package and mention that they are development requirements rather than general ones.

**Comment by nickforce989** [comment]
Is it reasonable now?
